apiVersion: apps/v1
kind: Deployment
metadata:
  name: videop_processing
  labels:
    app: videop_processing
spec:
  replicas: 1
  selector:
    matchLabels:
      app: videop_processing
  template:
    metadata:
      labels:
        app: videop_processing
    spec:
      containers:
        - name: videop_processing
          image: username/videop_processing:latest
          ports:
            - containerPort: 8080
          readinessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 10
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 10
          livenessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 120
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 5
